spring:
  mvc:
    pathmatch:
      matching-strategy: path_pattern_parser
  datasource:
    username: root
    password: '123456'
    url: jdbc:mysql://120.27.235.250:3306/project_wechat?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      enabled: true
      maxRequestSize: 1024MB
      maxFileSize: 1024MB
  redis:
    database: 0
    host: localhost
    port: 6379
    connect-timeout: 3000
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8081
  servlet:
    encoding:
      charset: utf-8
      enabled: true
  tomcat:
    uri-encoding: utf-8
    max-connections: 6500
    accept-count: 1000
    threads:
      min-spare: 500
      max: 2500
minio:
  endpoint: https://www.kfqty.com:9000
  accessKey: minioadmin
  secretKey: minioadmin
wechat:
  appid: wx593043cfbc3b7060
  secret: b76aedd7d30e00c548cc410e22479d5f